### ISSUE TITLE
webpack --watch causes infinite loop

### ISSUE THREAD

**Issue by drywolf** [Jimdo/typings-for-css-modules-loader#11]
As the title says, using the loader to generate .d.ts files in combination with webpack's watch mode runs in an endless cycle of the .d.ts files being generated, then triggering the webpack file-watchers and running the webpack compilation again over and over.

**Comment by diiq** [comment]
While it's not an _infinite_ loop for me (it settles down after 30 seconds to a minute), it is _very_ frustrating.

My solution has been to tell webpack not to watch '.d.ts' files -- I seem to be getting away with it.

```javascript
  ...
  plugins: [
    new webpack.WatchIgnorePlugin([
      /\.d\.ts$/
    ]),
    ...
]
```

**Comment by timse** [comment]
yes I was looking into fixing this, but loaders dont have the power to do so.
Should definitly be added to the README, luckily webpack ships it out of the box anyways :)
