### ISSUE TITLE
Question about persist.js code

### ISSUE THREAD

**Issue by scriby** [Jimdo/typings-for-css-modules-loader#22]
I was looking at the code in persist.js and had a couple observations.

```
export const writeToFileIfChanged = (filename, content) => {
  try {
    const currentInput = fs.readFileSync(filename, 'utf-8');
    const oldHash = crypto.createHash('md5').update(currentInput).digest('hex');
    const newHash = crypto.createHash('md5').update(content).digest('hex');
    // the definitions haven't changed - ignore this
    if (oldHash === newHash) {
      return false;
    }
  } finally {
    fs.writeFileSync(filename, content);
  }
};
```

Comments...

* Because the fs.writeFileSync is in the finally, it will write the file regardless of whether the `return false` statement is reached or not. If this was done on purpose, what was the reason?

* Because we have the full content of both files, there's not really a reason to compare hashes. It would be faster to compare them directly b/c it can short circuit, whereas the hash always has to process the full contents. I doubt this matters in the grand scheme of things, but it would simplify a bit.

**Comment by timse** [comment]
good points, would you mind open a PR, i guess we can do better on both points.
