### ISSUE TITLE
Not generating .d.ts files?

### ISSUE THREAD

**Issue by CmdrShepardsPie** [Jimdo/typings-for-css-modules-loader#27]
I'm giving this a shot but it doesn't seem to be working. I'm not sure what I'm missing, I dropped in this loader in place of css-loader as instructed.

I'm using WebPack 2 (webpack-dev-server) and TypeScript 2.2.1. Here's my loader config:
```
        test: /\.s?(a|c)ss$/,
        use: [
          'style-loader',
          // { loader: 'css-loader', options: { sourceMap: true, importLoaders: 3 } },
          { loader: 'typings-for-css-modules-loader', options: { sourceMap: true, importLoaders: 3, modules: true, namedExport: true, camelCase: true } },
          { loader: 'postcss-loader', options: { sourceMap: true } },
          { loader: 'resolve-url-loader', options: { sourceMap: true, root: path.resolve(__dirname, 'client') } },
          { loader: 'sass-loader', options: { sourceMap: true } }
        ] 
```

app.ts:
```
import style from './app.scss';
```

app.scss:
```
.app {
  color: red;
}
```

Two things to note, in order for TypeScript to load .scss files as modules, I added this to the custom-typings.d.ts file in my source folder:
```
declare module '*.scss' {
  const _: string;
  export default  _;
}
```

Anyway, not getting any .d.ts files, not getting any output in my console regarding this loader as far as I can tell, and not getting any types from my sass files. I'd think because I'm aliasing the .scss import as a string, it wouldn't work, so I'm curious if there's a different/better way to do that too.

Thanks!

**Comment by timse** [comment]
I guess its fine to have a mock module. Did u use the styles anywhere? It may be not considered as long as there is no usage of the styles anywhere

**Comment by CmdrShepardsPie** [comment]
Without the mock Module, TypeScript won't let me import the .scss, so I don't know how I would set it up otherwise. (Open to suggestions). 
App.ts is my entry point, so it uses that, and app.ts includes app.scss. Problem is I'm not getting any of the properties on my styles import from app.scss.

**Comment by timse** [comment]
Let me repeat: it is fine to have a mock module. 
Let me repeat too: are u using styles besides just importing it? As long as there is no use of the actual module webpack may not require it

**Comment by CmdrShepardsPie** [comment]
I misunderstood your question, no I wasn't using it (I'm an idiot), thus Webpack was tree shaking it.
Now that I'm actually using it, it's working!
Awesome! Thanks!

**Comment by timse** [comment]
Perfect 👌

**Comment by GobbaFish** [comment]
Hi, i am new to TypeScript development and am having the same problem where the .d.ts file isnt being generated. Sorry for the newbie question but what do you actually mean by ": are u using styles besides just importing it? "

**Comment by timse** [comment]
you need to use the imported styles in your code. If you just import them but not use them in the code they will be ignored.

and i will close this ;)

**Comment by jpap** [comment]
@CmdrShepardsPie, thanks for your mock module suggestion here.

It would really help to have this in the README! :D

**Comment by barbu110** [comment]
I am using my styles also and it's not generating the typings. What's wrong?

**Comment by manasb-uoe** [comment]
> you need to use the imported styles in your code. If you just import them but not use them in the code they will be ignored.
> 
> and i will close this ;)

This is exactly where I was going wrong! Thanks a lot!
