### ISSUE TITLE
build loop

### ISSUE THREAD

**Issue by CzBuCHi** [Jimdo/typings-for-css-modules-loader#35]
when i start webpack-dev-server i get 12 webpack rebuilds (last 6 catched by browser)

my build steps:
1) webpack-dev-server starts initial build
2) loader generates d.ts file
3) webpack see change in d.ts  and queue new build
4) browser starts loading
5) webpack start rebuilding -> step 2
6) after some time browser wds is initialized and starts refreshing modules (in my case around 6 build)
7) webpack gives up after 12 builds (guessing there is some sort of check for infinite build loop)
8) when i change some styles in css (no class change) -> webpack rebuild once
9) when i add new class in css -> webpack rebuild twice

start command:
```
webpack-dev-server --hot --history-api-fallback --config webpack.config.dev.js
```

configuration:
```js
{   
    module: {
        rules: [
            { test: /\.tsx?$/, exclude: /node_modules/, use: ['babel-loader', 'awesome-typescript-loader'] },
            { test: /\.css$/, exclude: /node_modules/, enforce: 'pre', use: ['style-loader', { loader: 'typings-for-css-modules-loader', options: { modules: true, namedExport: true } }] }
        ]
    },
    devtool: 'source-map',
    plugins: [
        new webpack.IgnorePlugin(/\.d\.ts$/),
        new webpack.NamedModulesPlugin()
    ],
    devServer: {
        port: 9000
    }
};

```
standart usage:
```tsx
import * as css from './style.css';

<div className={css.class}></div>
```

any idea how to remove additional builds when d.ts changes?

**Comment by timse** [comment]
no idea where the 12 builds come from, but generally the typings loader has to write to file to ensure that the IDE can pick up the typings file.
Webpack sees that as a new file and triggers a rebuild.
You can try to ignore d.ts file changes from the watcher - that may help :)

**Comment by CzBuCHi** [comment]
@timse  thats was my thoughts too .. that why i have `new webpack.IgnorePlugin(/\.d\.ts$/),` in there ... im guessing, that this is not how to tell watcher to ignore these files ... :(

**Comment by kohlikohl** [comment]
The issue seems to be with https://github.com/webpack/watchpack/issues/25.
Following the suggestion from https://github.com/webpack/watchpack/issues/25#issuecomment-319292564 comment solves it.

Added following to the config:
```js

plugins: [
        // Preventing compilation loop when new style.d.ts file is created
        {
            apply: function (compiler) {
                const timefix = 11000;
                compiler.plugin('watch-run', (watching, callback) => {
                    watching.startTime += timefix;
                    callback()
                });
                compiler.plugin('done', (stats) => {
                    stats.startTime -= timefix
                })
            }
        }
    ]
```

The solution to just ignore `*.d.ts` files seems more elegant though.

**Comment by Jack-Barry** [comment]
This was driving me nuts. Every time I made a change in a `.css` file and saved it I was getting stuck in an endless loop of recompiles. @CzBuCHi's comment did the trick, thank you sir!
