### ISSUE TITLE
readme need refresh

### ISSUE THREAD

**Issue by guotie** [Jimdo/typings-for-css-modules-loader#38]
When i use typescript 2.4 and the latest typings-for-css-modules-loader, it will convert sass file as follow:

sytle.sass：
```sass
$font-stack:    Helvetica, sans-serif
$primary-color: #333

.some-class
  font: 100% $font-stack
  color: $primary-color

```

to style.sass.d.ts:
```ts
export interface IStyleSass {
  'some-class': string;
}

export const locals: IStyleSass;

```

so, in the ts file, when I import it as follow:
```ts
import style from './styles.sass'
```

error occurs:
```
error TS1192: Module '"xxxxx/xxxx/src/style.sass"' has no default export.
```

so, it should be imported as following:

```ts
import * as styles from './style.sass';
```
then, it works!

**Comment by timse** [comment]
would you mind to open a pr for that? :)

**Comment by guotie** [comment]
https://github.com/Jimdo/typings-for-css-modules-loader/pull/43

the example is a gif, I don't know how to make a gif, so I commented blow the gif.
