### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by valoricDe** [Jimdo/typings-for-css-modules-loader#54]
Thank you for this great module.
With css-loader I can include css-loader/locals to only export the classnames and not embed them in the bundle. How would I do that in this module?

currently I have the following in my webpack config:
```
...
loader: server ? "css-loader/locals" : "css-loader",
    options: {
      modules: true,
      importLoaders: !server,
      localIdentName: "[name]__[local]--[hash:base64:5]"
    }
...
```

**Comment by shiro** [comment]
Anything changed about SSR support?
Some work-around at least?

**Comment by sentilesdal** [comment]
I'm also blocked on this.  The style-loader breaks on server side renders since there is no global 'window' object.  Would love to use this package!

**Comment by valoricDe** [comment]
Hi @sentilesdal Does the style-loader require the window object? With style-loader you refer to `typings-for-css-modules-loader` right?

**Comment by sentilesdal** [comment]
@valorize yes, the style loader requires the window object. I'm refering to the [style-loader](https://github.com/webpack-contrib/style-loader) package.  When using the following setup in my webpack config: 
```
      test: /\.(scss|css)$/,
      use: [
        'style-loader',
        {
          loader: 'typings-for-css-modules-loader',
          options: {
            modules: true,
            namedExport: true,
            sourceMap: true,
            importLoaders: 3,
            localIdentName: '[name]__[local]__[hash:base64:5]',
          },
        },
```
I'll get the following error when I try to build our server side bundle:
```
[server.js] ReferenceError: window is not defined
[server.js]     at  ./node_modules/style-loader/lib/addStyles.js:23:1
[server.js]     at  ./node_modules/style-loader/lib/addStyles.js:12:1
```

I'm using universal-webpack to handle the SSR.

**Comment by ajliv** [comment]
@sentilesdal I'm pretty sure you just need to remove `style-loader` from your server webpack config and only include it in the client one. `style-loader`'s purpose is "Adds CSS to the DOM by injecting a <style> tag"

**Comment by ugnb** [comment]
Using [isomorphic-style-loader](https://github.com/kriasoft/isomorphic-style-loader) instead `style-loader` solved it for me.

**Comment by valoricDe** [comment]
I'm not using css modules currently therefore I close this issue and hope that isomorphic-style-loader will solve it for all
