### ISSUE TITLE
Node crashes when trying to use CSS modules 'composes'

### ISSUE THREAD

**Issue by AlexanderMattoni** [Jimdo/typings-for-css-modules-loader#6]
If I have the following sass class:

.new {
    composes: test from "./test.scss";  
}

and in ./test.scss:

.test {
    color: red;
}
compiling gives me the following error, then node crashes:

(node:26366) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'length' of undefined

Removing the composes fixes the issue, but it works with regular css-loader.

Would love to be able to utilize css module composition in conjunction with this.

**Comment by timse** [comment]
thanks for reporting, i will take a look!

**Comment by timse** [comment]
hey @AlexanderMattoni looking into it, not that simple, will keep you posted.

However the errors im getting is a bit different. can you tell me how to reproduce yours?

**Comment by scriby** [comment]
I've been trying to get compose imports to work as well. I always get "Cannot find module" errors no matter how I reference the path.
